In [22]:
import pandas as pd

ruta_csv = r'C:\Users\fmascava\Desktop\Proyecto de ML - Ingenieria Core\dataset\ookla_MobileNetworkPerformance_agosto.csv'

# Lee el archivo CSV
df = pd.read_csv(ruta_csv, sep=";")

# Muestra las primeras filas del DataFrame
df.head()

C:\Users\fmascava\AppData\Local\Temp\ipykernel_6916\3895799005.py:6: DtypeWarning: Columns (66,86,129) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_csv, sep=";")

,id_result,guid_result,id_platform,ts_result,ts_result_received,attr_location_timezone,id_device,attr_device_android_fingerprint,attr_device_model,attr_device_manufacturer,...,is_portal_included,attr_portal_categories,attr_connection_type_start_string,attr_connection_type_end_string,attr_device_esim_embedded,id_cell_nr,id_cell_start,attr_network_operator_mcc_nr,attr_network_operator_mnc_nr,created
0,10279396645,9E1EC06782204FD7B88A66F4ED7C62C5,1,2024-08-01T13:50:19.000Z,2024-08-01T13:50:19.000Z,America/Santiago,460172689,senter/s337v6OG/lahaina:12/SKQ1.211202.001/eng...,Unknown Device,Unknown,...,False,NaN,Unknown,Unknown,NaN,NaN,3098519.0,0,0,2024-08-02 02:03:30.000
1,10280316378,31D5204CA10449C2B438233C67221327,1,2024-08-01T22:25:25.000Z,2024-08-01T22:25:25.000Z,America/Santiago,477326868,motorola/fogos_gn/fogos:14/U1UG34.23-28-2/8dca...,NaN,NaN,...,True,"5G,All Cell",NRNSA,NRNSA,False,2.147484e+09,159766559.0,730,2,2024-08-02 02:03:30.000
2,10280322383,AD87322E909F40BB849F93D195144769,1,2024-08-01T22:30:33.000Z,2024-08-01T22:30:33.000Z,America/Santiago,477326868,motorola/fogos_gn/fogos:14/U1UG34.23-28-2/8dca...,NaN,NaN,...,True,"5G,All Cell",NRNSA,NRNSA,False,NaN,11204188.0,730,2,2024-08-02 02:03:30.000
3,6210510294,AC4968345A0740B591B82EFEBE85D727,2,2024-08-01T15:27:21.000Z,2024-08-01T15:27:21.000Z,America/Santiago,263596824,NaN,iPhone 14 Pro,Apple,...,True,"5G Capable,All Cell,LTE,Modern Chipset",LTE,LTE,NaN,NaN,NaN,0,0,2024-08-02 02:03:30.000
4,10279416889,D03E2CDA5B6E4177AFF7048C3B316CC3,1,2024-08-01T14:00:00.000Z,2024-08-01T14:00:00.000Z,America/Santiago,477496386,samsung/b4qxxx/b4q:14/UP1A.231005.007/F721BXXS...,Galaxy Z Flip4,Samsung,...,True,"5G Capable,All Cell,LTE,Modern Chipset",LTE,LTE,NaN,NaN,204545.0,0,0,2024-08-02 02:03:30.000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100687 entries, 0 to 100686
Columns: 175 entries, id_result to created
dtypes: bool(2), float64(83), int64(17), object(73)
memory usage: 133.1+ MB

In [16]:
df.describe()

,id_result,id_platform,id_device,attr_device_ram_mb,attr_device_storage_mb,attr_device_multi_sim_support,num_device_active_modems,num_device_supported_modems,attr_device_service_state,attr_device_thermal_status,...,attr_cell_nr_pci,attr_cell_tac,attr_cell_lac,attr_cell_psc,attr_cell_frequency_channel,attr_cell_nr_arfcn,id_cell_nr,id_cell_start,attr_network_operator_mcc_nr,attr_network_operator_mnc_nr
count,1.006870e+05,100687.000000,1.006870e+05,77602.000000,100245.000000,52389.000000,68088.000000,68088.000000,53204.000000,71270.000000,...,5886.000000,100687.000000,3329.000000,3327.000000,100687.000000,6268.000000,4.961000e+03,5.577600e+04,100687.000000,100687.000000
mean,9.379116e+09,1.225541,4.033867e+08,6437.864230,132261.519517,0.140965,1.864117,1.886603,0.006278,0.072808,...,326.897044,4907.661992,28629.458396,229.876465,5554.959349,628848.310147,1.595247e+09,2.189868e+07,344.541768,1.534349
std,1.703832e+09,0.417940,8.352919e+07,2413.607835,117399.320006,0.347988,0.347603,0.322818,0.081097,0.374719,...,250.073936,10713.323580,23369.311471,152.151646,16057.933566,12942.523526,8.813570e+08,4.609763e+07,364.413327,3.781076
min,6.209646e+09,1.000000,7.741294e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,2.860000e+02,0.000000,0.000000
25%,1.027992e+10,1.000000,3.485425e+08,5252.000000,51831.000000,0.000000,2.000000,2.000000,0.000000,0.000000,...,127.000000,0.000000,8506.000000,89.500000,0.000000,620736.000000,2.684355e+08,2.318694e+06,0.000000,0.000000
50%,1.029089e+10,1.000000,4.436619e+08,5662.000000,113579.000000,0.000000,2.000000,2.000000,0.000000,0.000000,...,276.000000,0.000000,26011.000000,216.000000,0.000000,624960.000000,2.147484e+09,4.041473e+06,0.000000,0.000000
75%,1.030673e+10,1.000000,4.697559e+08,7493.000000,231546.000000,0.000000,2.000000,2.000000,0.000000,0.000000,...,454.000000,5104.000000,55700.000000,361.000000,3100.000000,641666.000000,2.147484e+09,1.117588e+07,730.000000,2.000000
max,1.032184e+10,2.000000,4.792282e+08,17412.000000,976499.000000,1.000000,3.000000,3.000000,3.000000,4.000000,...,1007.000000,64405.000000,64405.000000,511.000000,66961.000000,643392.000000,2.147484e+09,2.147484e+09,999.000000,310.000000

In [23]:
# Seleccionar variables de interÃ©s
variables_interes = [
    # IdentificaciÃ³n de la prueba
    'id_result', 'guid_result', 'ts_result', 'id_platform',
    
    # InformaciÃ³n del dispositivo
    'attr_device_model', 'attr_device_manufacturer', 'attr_device_os_version',
    
    # InformaciÃ³n de la red y SIM
    'attr_sim_operator_common_name', 'attr_network_operator_common_name',
    'attr_network_operator_mcc', 'attr_network_operator_mnc',
    'attr_connection_type_start_string', 'attr_connection_type_end_string',
    
    # UbicaciÃ³n geogrÃ¡fica
    'attr_location_latitude', 'attr_location_longitude', 'attr_location_accuracy_m','attr_place_region','attr_place_subregion',
    
    # Indicadores de calidad de seÃ±al
    'val_download_kbps', 'val_upload_kbps', 'val_latency_min_ms',
    'val_multiserver_latency_ms', 'val_jitter_ms', 'val_traceroute0_latency_ms',
    'val_server_distance_km',
    
    # MÃ©tricas especÃ­ficas de seÃ±al celular
    'val_signal_rsrp_dbm', 'val_signal_rsrq_db', 'val_signal_rssi_dbm', 'val_signal_cqi',

    
    # Uso de NR (National Roaming)
    'is_device_data_roaming_enabled', 'attr_connection_nr_state'
]

df = df[variables_interes]

# Mostrar las primeras filas del DataFrame con las variables seleccionadas
df.head()

,id_result,guid_result,ts_result,id_platform,attr_device_model,attr_device_manufacturer,attr_device_os_version,attr_sim_operator_common_name,attr_network_operator_common_name,attr_network_operator_mcc,...,val_multiserver_latency_ms,val_jitter_ms,val_traceroute0_latency_ms,val_server_distance_km,val_signal_rsrp_dbm,val_signal_rsrq_db,val_signal_rssi_dbm,val_signal_cqi,is_device_data_roaming_enabled,attr_connection_nr_state
0,10279396645,9E1EC06782204FD7B88A66F4ED7C62C5,2024-08-01T13:50:19.000Z,1,Unknown Device,Unknown,31,NaN,NaN,NaN,...,NaN,0.4,1.0,10,NaN,NaN,NaN,NaN,NaN,NaN
1,10280316378,31D5204CA10449C2B438233C67221327,2024-08-01T22:25:25.000Z,1,NaN,NaN,34,Movistar,Movistar,730.0,...,NaN,2.1,3000.0,2,-59.0,-14.0,NaN,NaN,False,3.0
2,10280322383,AD87322E909F40BB849F93D195144769,2024-08-01T22:30:33.000Z,1,NaN,NaN,34,Movistar,Movistar,730.0,...,NaN,6.9,53.0,60,NaN,NaN,-120.0,NaN,False,0.0
3,6210510294,AC4968345A0740B591B82EFEBE85D727,2024-08-01T15:27:21.000Z,2,iPhone 14 Pro,Apple,17.5.1,Entel,NaN,NaN,...,38.4767,5.6,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
4,10279416889,D03E2CDA5B6E4177AFF7048C3B316CC3,2024-08-01T14:00:00.000Z,1,Galaxy Z Flip4,Samsung,34,Claro,Claro,730.0,...,23.8116,2.8,NaN,10,-68.0,-9.0,NaN,NaN,NaN,NaN

In [ ]:
# Verificar columnas presentes y faltantes
columnas_presentes = [col for col in variables_interes if col in df.columns]
columnas_faltantes = [col for col in variables_interes if col not in df.columns]

print("Columnas presentes:", columnas_presentes)
print("Columnas faltantes:", columnas_faltantes)

# Seleccionar solo las columnas presentes
df = df[columnas_presentes]

# Mostrar las primeras filas del DataFrame con las variables seleccionadas

Columnas presentes: ['id_result', 'guid_result', 'ts_result', 'id_platform', 'attr_device_model', 'attr_device_manufacturer', 'attr_device_os_version', 'attr_sim_operator_common_name', 'attr_network_operator_common_name', 'attr_network_operator_mcc', 'attr_network_operator_mnc', 'attr_connection_type_start_string', 'attr_connection_type_end_string', 'attr_location_latitude', 'attr_location_longitude', 'attr_location_accuracy_m', 'attr_place_region', 'attr_place_subregion', 'val_download_kbps', 'val_upload_kbps', 'val_latency_min_ms', 'val_multiserver_latency_ms', 'val_jitter_ms', 'val_traceroute0_latency_ms', 'val_server_distance_km', 'val_signal_rsrp_dbm', 'val_signal_rsrq_db', 'val_signal_rssi_dbm', 'val_signal_cqi', 'is_device_data_roaming_enabled', 'attr_connection_nr_state']
Columnas faltantes: []

,id_result,guid_result,ts_result,id_platform,attr_device_model,attr_device_manufacturer,attr_device_os_version,attr_sim_operator_common_name,attr_network_operator_common_name,attr_network_operator_mcc,...,val_multiserver_latency_ms,val_jitter_ms,val_traceroute0_latency_ms,val_server_distance_km,val_signal_rsrp_dbm,val_signal_rsrq_db,val_signal_rssi_dbm,val_signal_cqi,is_device_data_roaming_enabled,attr_connection_nr_state
0,10279396645,9E1EC06782204FD7B88A66F4ED7C62C5,2024-08-01T13:50:19.000Z,1,Unknown Device,Unknown,31,NaN,NaN,NaN,...,NaN,0.4,1.0,10,NaN,NaN,NaN,NaN,NaN,NaN
1,10280316378,31D5204CA10449C2B438233C67221327,2024-08-01T22:25:25.000Z,1,NaN,NaN,34,Movistar,Movistar,730.0,...,NaN,2.1,3000.0,2,-59.0,-14.0,NaN,NaN,False,3.0
2,10280322383,AD87322E909F40BB849F93D195144769,2024-08-01T22:30:33.000Z,1,NaN,NaN,34,Movistar,Movistar,730.0,...,NaN,6.9,53.0,60,NaN,NaN,-120.0,NaN,False,0.0
3,6210510294,AC4968345A0740B591B82EFEBE85D727,2024-08-01T15:27:21.000Z,2,iPhone 14 Pro,Apple,17.5.1,Entel,NaN,NaN,...,38.4767,5.6,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
4,10279416889,D03E2CDA5B6E4177AFF7048C3B316CC3,2024-08-01T14:00:00.000Z,1,Galaxy Z Flip4,Samsung,34,Claro,Claro,730.0,...,23.8116,2.8,NaN,10,-68.0,-9.0,NaN,NaN,NaN,NaN

In [26]:
#filtra solo terminales android
df_filtered = df[df['id_platform'] == 1]

In [27]:
import matplotlib.pyplot as plt

In [28]:
# Obtener la distribuciÃ³n por regiÃ³n
region_distribution = df['attr_place_region'].value_counts()

# Mostrar la distribuciÃ³n
print(region_distribution)

attr_place_region
Santiago Metropolitan Region                57072
BÃ­o BÃ­o Region                               7642
Valparaiso                                   6815
Araucania                                    5333
O'Higgins Region                             5301
Maule Region                                 4764
Los Lagos Region                             3468
Coquimbo Region                              2671
Antofagasta Region                           1746
Los RÃ­os Region                              1695
Atacama Region                               1252
TarapacÃ¡ Region                              1035
Arica y Parinacota Region                     784
Magallanes y la AntÃ¡rtica Chilena Region      523
AysÃ©n                                         370
Name: count, dtype: int64

In [30]:
df.describe()

,id_result,id_platform,attr_network_operator_mcc,attr_network_operator_mnc,attr_location_latitude,attr_location_longitude,attr_location_accuracy_m,val_download_kbps,val_upload_kbps,val_latency_min_ms,val_multiserver_latency_ms,val_jitter_ms,val_traceroute0_latency_ms,val_server_distance_km,val_signal_rsrp_dbm,val_signal_rsrq_db,val_signal_rssi_dbm,val_signal_cqi,attr_connection_nr_state
count,1.006870e+05,100687.000000,74762.000000,74762.000000,100687.000000,100687.000000,74698.000000,1.006870e+05,1.006870e+05,100687.000000,73162.000000,100637.000000,84219.000000,100687.000000,41603.000000,41688.000000,2171.000000,11211.000000,43981.000000
mean,9.379116e+09,1.225541,729.854579,3.401099,-34.064571,-71.165302,194.619481,9.045625e+04,6.613781e+04,40.439878,80.002862,47.088201,1851.465560,145.715673,-98.177463,-12.269598,-64.270382,9.850682,0.924854
std,1.703832e+09,0.417940,8.309041,7.444726,3.728810,1.091298,905.939446,1.652565e+05,6.769308e+06,81.177281,158.502365,134.608997,1413.810485,550.629051,12.429422,3.069043,38.108506,8.186225,1.321996
min,6.209646e+09,1.000000,204.000000,1.000000,-54.936000,-109.437000,1.000000,1.000000e+00,1.000000e+00,0.000000,3.105800,0.100000,0.000000,0.000000,-161.000000,-100.000000,-120.000000,0.000000,0.000000
25%,1.027992e+10,1.000000,730.000000,1.000000,-34.580000,-71.516000,13.000000,5.539000e+03,3.129000e+03,18.000000,30.810750,4.800000,128.000000,2.000000,-107.000000,-14.000000,-95.000000,8.000000,0.000000
50%,1.029089e+10,1.000000,730.000000,2.000000,-33.452000,-70.697000,31.000000,2.675300e+04,1.021500e+04,25.000000,41.264750,9.000000,3000.000000,13.000000,-100.000000,-12.000000,-71.000000,10.000000,0.000000
75%,1.030673e+10,1.000000,730.000000,3.000000,-33.418000,-70.653000,73.000000,9.698550e+04,2.572100e+04,36.000000,62.230525,22.100000,3001.000000,93.000000,-92.000000,-10.000000,-24.000000,11.000000,3.000000
max,1.032184e+10,2.000000,999.000000,869.000000,-17.985000,-67.602000,65535.000000,1.101782e+06,2.147484e+09,2840.000000,7054.280300,999.900000,7261.000000,18638.000000,0.000000,0.000000,-1.000000,255.000000,3.000000

In [31]:
# Obtener la distribuciÃ³n por regiÃ³n
region_distribution = df['attr_place_region'].value_counts()

# Mostrar la distribuciÃ³n
print(region_distribution)

attr_place_region
Santiago Metropolitan Region                57072
BÃ­o BÃ­o Region                               7642
Valparaiso                                   6815
Araucania                                    5333
O'Higgins Region                             5301
Maule Region                                 4764
Los Lagos Region                             3468
Coquimbo Region                              2671
Antofagasta Region                           1746
Los RÃ­os Region                              1695
Atacama Region                               1252
TarapacÃ¡ Region                              1035
Arica y Parinacota Region                     784
Magallanes y la AntÃ¡rtica Chilena Region      523
AysÃ©n                                         370
Name: count, dtype: int64

In [32]:
# Obtener la distribuciÃ³n por operador comÃºn
operator_distribution = df['attr_sim_operator_common_name'].value_counts()

# Mostrar la distribuciÃ³n
print(operator_distribution)

attr_sim_operator_common_name
Entel                     41393
WOM                       22042
Movistar                  19923
Claro                     11694
VTR                        1061
Vivo                         50
AT&T                         24
VIVA                         24
Personal                     19
TIM                          18
Tigo                         16
Bitel                        14
T-Mobile                     14
Verizon Wireless              8
Antel                         7
Unknown                       6
Taiwan Mobile                 6
China Mobile Hong Kong        4
TELUS                         4
3                             4
Zain                          3
Orange                        3
Turkcell                      3
Vodafone                      3
Telstra                       2
au                            2
Safaricom                     2
Irancell                      2
Americanet                    2
Salt                          2
U Mobile                      1
Plus                          1
Cubacel                       1
Videotron                     1
Digitel                       1
KPN Mobile                    1
MegaFon                       1
Beeline                       1
Swisscom                      1
StarHub                       1
MTN                           1
Hamrah-e-Aval                 1
Jio                           1
Odido                         1
Rogers                        1
Bell                          1
Name: count, dtype: int64

In [33]:
# Obtener la distribuciÃ³n por operador comÃºn
operatornet_distribution = df['attr_network_operator_common_name'].value_counts()

# Mostrar la distribuciÃ³n
print(operatornet_distribution)

attr_network_operator_common_name
Entel            30153
Movistar         16783
WOM              15818
Claro            12012
VIVA                41
Vivo                18
Tigo                17
Bitel               15
TIM                  9
Personal             8
Zain                 3
Turkcell             3
Safaricom            2
Vodafone             2
AT&T                 2
Cubacel              1
Telenor              1
Kyivstar             1
Digitel              1
U Mobile             1
T-Mobile             1
Hamrah-e-Aval        1
Salt                 1
Beeline              1
MTN                  1
MegaFon              1
Jio                  1
Odido                1
Telcel               1
Name: count, dtype: int64

In [34]:
# Filtrar los datos para los usuarios que estÃ¡n en la red propia de WOM
df_WOM = df[(df['attr_sim_operator_common_name'] == 'WOM') & 
            (df['attr_network_operator_common_name'] == 'WOM')]

# Filtrar los datos para los usuarios que estÃ¡n en NR (National Roaming)
df_NR = df[(df['attr_sim_operator_common_name'] == 'WOM') & 
           (df['attr_network_operator_common_name'] != 'WOM')]

# Mostrar las primeras filas de cada DataFrame para verificar
print("Usuarios en la red propia de WOM:")
print(df_WOM.head())

print("\nUsuarios en NR (National Roaming):")
print(df_NR.head())

Usuarios en la red propia de WOM:
      id_result                       guid_result                 ts_result  \
23  10279297998  E4552EAE1D5B4C218EA8B377C4D79AD4  2024-08-01T13:03:01.000Z
33  10279933136  C87ED3F25F454CFEAD156684053D3EE4  2024-08-01T18:16:12.000Z
40  10279630650  B46E8B73F4AD420FB10179D2EFADB699  2024-08-01T15:42:08.000Z
41  10279625439  C127E59312E2419EB1E2DB9CF7E1E92D  2024-08-01T15:39:40.000Z
42  10280335978  319F14F758824D9CB0DC4FB2BB4CB800  2024-08-01T22:42:04.000Z

    id_platform attr_device_model attr_device_manufacturer  \
23            1  Galaxy S21 FE 5G                  Samsung
33            1               P30                   Huawei
40            1     Mi 10T Pro 5G                   Xiaomi
41            1     Mi 10T Pro 5G                   Xiaomi
42            1    Edge 30 Fusion                 Motorola

   attr_device_os_version attr_sim_operator_common_name  \
23                     34                           WOM
33                     29                           WOM
40                     31                           WOM
41                     31                           WOM
42                     33                           WOM

   attr_network_operator_common_name  attr_network_operator_mcc  ...  \
23                               WOM                      730.0  ...
33                               WOM                      730.0  ...
40                               WOM                      730.0  ...
41                               WOM                      730.0  ...
42                               WOM                      730.0  ...

    val_multiserver_latency_ms val_jitter_ms val_traceroute0_latency_ms  \
23                     19.0557           4.8                     3000.0
33                     54.2798         200.8                     3000.0
40                         NaN         190.9                     3003.0
41                    229.9735         772.0                     3005.0
42                     17.5058           2.0                     3001.0

    val_server_distance_km  val_signal_rsrp_dbm  val_signal_rsrq_db  \
23                       3                -76.0                -6.0
33                     216               -112.0               -11.0
40                      33                  NaN                 NaN
41                      33                  NaN                 NaN
42                      14               -112.0               -12.0

   val_signal_rssi_dbm val_signal_cqi  is_device_data_roaming_enabled  \
23                 NaN           12.0                             NaN
33                 NaN            NaN                            True
40                 NaN            NaN                            True
41                 NaN            NaN                            True
42                 NaN            NaN                            True

    attr_connection_nr_state
23                       NaN
33                       0.0
40                       NaN
41                       NaN
42                       3.0

[5 rows x 31 columns]

Usuarios en NR (National Roaming):
      id_result                       guid_result                 ts_result  \
18   6211036251  801C7F73022141F398A94D091920038D  2024-08-01T23:00:01.000Z
19   6209933387  EEFA7B62570A4AE0BDB5CD4C22050778  2024-08-01T06:10:03.000Z
22   6209933816  F4B08DFA094743C78F54A1DFAB6A19D7  2024-08-01T06:10:38.000Z
24   6209934741  36F0E1BC6C2F418A9A2130A4318E4D93  2024-08-01T06:11:48.000Z
38  10280375492  B6643A68E1C4487187CED535163070C2  2024-08-01T23:16:39.000Z

    id_platform  attr_device_model attr_device_manufacturer  \
18            2  iPhone 11 Pro Max                    Apple
19            2  iPhone 13 Pro Max                    Apple
22            2  iPhone 13 Pro Max                    Apple
24            2  iPhone 13 Pro Max                    Apple
38            1      Mi 11 Lite 5G                   Xiaomi

   attr_device_os_version attr_sim_operator_common_name  \
18                   17.6                           WOM
19                   17.6                           WOM
22                   17.6                           WOM
24                   17.6                           WOM
38                     33                           WOM

   attr_network_operator_common_name  attr_network_operator_mcc  ...  \
18                               NaN                        NaN  ...
19                               NaN                        NaN  ...
22                               NaN                        NaN  ...
24                               NaN                        NaN  ...
38                             Claro                      730.0  ...

    val_multiserver_latency_ms val_jitter_ms val_traceroute0_latency_ms  \
18                     32.2122           3.8                        NaN
19                         NaN           3.9                        NaN
22                         NaN           4.5                        NaN
24                         NaN           5.6                        NaN
38                     60.3397          32.4                     3002.0

    val_server_distance_km  val_signal_rsrp_dbm  val_signal_rsrq_db  \
18                      58                  NaN                 NaN
19                       9                  NaN                 NaN
22                       9                  NaN                 NaN
24                       9                  NaN                 NaN
38                     134               -100.0                -9.0

   val_signal_rssi_dbm val_signal_cqi  is_device_data_roaming_enabled  \
18                 NaN            NaN                             NaN
19                 NaN            NaN                             NaN
22                 NaN            NaN                             NaN
24                 NaN            NaN                             NaN
38                 NaN            NaN                            True

    attr_connection_nr_state
18                       NaN
19                       NaN
22                       NaN
24                       NaN
38                       0.0

[5 rows x 31 columns]